[package]
name = "codex-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
codex-config-diagnostics = { workspace = true }
codex-config-edit = { workspace = true }
codex-config-local-loader = { workspace = true }
codex-config-loader = { workspace = true }
codex-config-permissions = { workspace = true }
codex-config-requirements = { workspace = true }
codex-config-state = { workspace = true }
codex-config-toml = { workspace = true }
codex-config-types = { workspace = true }
codex-protocol = { workspace = true }
codex-utils-absolute-path = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[lib]
doctest = false
