[package]
name = "app-server-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "app_server_protocol"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[features]
cli = ["dep:clap"]

[[bin]]
name = "export"
path = "src/bin/export.rs"
required-features = ["cli"]

[[bin]]
name = "write_schema_fixtures"
path = "src/bin/write_schema_fixtures.rs"
required-features = ["cli"]

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true, features = ["derive"], optional = true }
codex-auth-types = { workspace = true }
codex-config-types = { workspace = true }
codex-connectors-api = { workspace = true }
codex-experimental-api-macros = { workspace = true }
jsonrpc-types = { workspace = true }
mcp-types = { workspace = true }
plugin-service-api = { workspace = true }
protocol = { workspace = true }
codex-shell-utils = { workspace = true }
codex-utils-absolute-path = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
shlex = { workspace = true }
strum_macros = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-bash = { workspace = true }
rmcp = { workspace = true, default-features = false, features = [
    "base64",
    "macros",
    "schemars",
    "server",
] }
ts-rs = { workspace = true }
inventory = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v7"] }

[dev-dependencies]
anyhow = { workspace = true }
codex-utils-cargo-bin = { workspace = true }
pretty_assertions = { workspace = true }
similar = { workspace = true }
tempfile = { workspace = true }
