pub mod config_layers;
pub mod installed_marketplaces;
pub mod loader;
mod manager;
pub mod manifest;
pub mod marketplace;
pub mod marketplace_add;
pub mod marketplace_remove;
pub mod marketplace_upgrade;
pub mod remote_state;
pub mod startup_sync;
pub mod store;
#[cfg(test)]
mod test_support;
pub mod toggles;

pub type LoadedPlugin = codex_plugin::LoadedPlugin<codex_config_types::McpServerConfig>;
pub type PluginLoadOutcome = codex_plugin::PluginLoadOutcome<codex_config_types::McpServerConfig>;

pub use codex_core_plugins_api::OPENAI_BUNDLED_MARKETPLACE_NAME;
pub use codex_core_plugins_api::OPENAI_CURATED_MARKETPLACE_NAME;
pub use codex_core_plugins_api::PluginsConfigInput;
pub use codex_core_plugins_api::TOOL_SUGGEST_DISCOVERABLE_PLUGIN_ALLOWLIST;
pub use codex_core_plugins_api::config_layers::PluginConfigLayerEntry;
pub use codex_core_plugins_api::config_layers::PluginConfigLayerStack;
pub use manager::ConfiguredMarketplace;
pub use manager::ConfiguredMarketplaceListOutcome;
pub use manager::ConfiguredMarketplacePlugin;
pub use manager::PluginAnalyticsEventSink;
pub use manager::PluginDetail;
pub use manager::PluginDetailsUnavailableReason;
pub use manager::PluginInstallError;
pub use manager::PluginInstallOutcome;
pub use manager::PluginInstallRequest;
pub use manager::PluginReadOutcome;
pub use manager::PluginReadRequest;
pub use manager::PluginUninstallError;
pub use manager::PluginsManager;
pub use manager::configured_plugins_from_stack;
pub use marketplace_upgrade::ConfiguredMarketplaceUpgradeError as PluginMarketplaceUpgradeError;
pub use marketplace_upgrade::ConfiguredMarketplaceUpgradeOutcome as PluginMarketplaceUpgradeOutcome;
