[package]
name = "mcp-service-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "mcp_service_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-channel = { workspace = true }
codex-approval-service-api = { workspace = true }
codex-auth-types = { workspace = true }
config-service = { workspace = true }
codex-config-types = { workspace = true }
codex-connectors-api = { workspace = true }
skill-service-api = { workspace = true }
tool-config = { workspace = true }
exec-server-api = { workspace = true }
mcp-types = { workspace = true }
codex-openai-files-api = { workspace = true }
protocol = { workspace = true }
plugin-service-api = { workspace = true }
thread-service-api = { workspace = true }
codex-utils-output-truncation = { workspace = true }
codex-tool-service-api = { workspace = true }
http = { workspace = true }
serde_json = { workspace = true }
tokio-util = { workspace = true, features = ["rt"] }
