[package]
edition.workspace = true
license.workspace = true
name = "codex-core-plugins-api"
version.workspace = true

[lib]
doctest = false
name = "codex_core_plugins_api"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
codex-config-types = { workspace = true }
codex-plugin-types = { workspace = true }
codex-utils-absolute-path = { workspace = true }
toml = { workspace = true }
