[package]
edition.workspace = true
license.workspace = true
name = "metrics-api"
version.workspace = true

[lib]
doctest = false
name = "metrics_api"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
codex-utils-string = { workspace = true }
serde = { workspace = true, features = ["derive"] }
