// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

export type PluginInterface = { displayName: string | null, shortDescription: string | null, longDescription: string | null, developerName: string | null, category: string | null, capabilities: Array<string>, websiteUrl: string | null, privacyPolicyUrl: string | null, termsOfServiceUrl: string | null, defaultPrompt: Array<string> | null, brandColor: string | null, composerIcon: AbsolutePathBuf | null, composerIconUrl: string | null, logo: AbsolutePathBuf | null, logoUrl: string | null, screenshots: Array<AbsolutePathBuf>, screenshotUrls: Array<string>, };
