// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadActiveFlag } from "./ThreadActiveFlag";
import type { ThreadIdleReason } from "./ThreadIdleReason";

export type ThreadStatus = { "type": "notLoaded" } | { "type": "idle", reason: ThreadIdleReason, } | { "type": "complete" } | { "type": "systemError" } | { "type": "active", activeFlags: Array<ThreadActiveFlag>, };
