// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSkillKind } from "./ThreadSkillKind";

export type ThreadSkill = { name: string, path: string, kind: ThreadSkillKind, };
