// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadWorkflowRunProgressKind } from "./ThreadWorkflowRunProgressKind";

export type ThreadWorkflowRunProgressEvent = { runId: string, workflowId: string, status: unknown, runnerStatus: string, kind: ThreadWorkflowRunProgressKind, message: string, updatedAt: number, };
