// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { MessagePhase } from "../MessagePhase";
import type { ReasoningEffort } from "../ReasoningEffort";
import type { JsonValue } from "../serde_json/JsonValue";
import type { CollabAgentOperation } from "./CollabAgentOperation";
import type { CollabAgentState } from "./CollabAgentState";
import type { CollabAgentTool } from "./CollabAgentTool";
import type { CollabAgentToolCallStatus } from "./CollabAgentToolCallStatus";
import type { CommandAction } from "./CommandAction";
import type { CommandExecutionNotificationKind } from "./CommandExecutionNotificationKind";
import type { CommandExecutionNotifyOn } from "./CommandExecutionNotifyOn";
import type { CommandExecutionSource } from "./CommandExecutionSource";
import type { CommandExecutionStatus } from "./CommandExecutionStatus";
import type { CommandWaitNotificationKind } from "./CommandWaitNotificationKind";
import type { CommandWaitStatus } from "./CommandWaitStatus";
import type { DynamicToolCallOutputContentItem } from "./DynamicToolCallOutputContentItem";
import type { DynamicToolCallStatus } from "./DynamicToolCallStatus";
import type { FileUpdateChange } from "./FileUpdateChange";
import type { HookPromptFragment } from "./HookPromptFragment";
import type { InjectedContextSection } from "./InjectedContextSection";
import type { McpToolCallError } from "./McpToolCallError";
import type { McpToolCallResult } from "./McpToolCallResult";
import type { McpToolCallStatus } from "./McpToolCallStatus";
import type { MemoryCitation } from "./MemoryCitation";
import type { PatchApplyStatus } from "./PatchApplyStatus";
import type { ThreadEventCommandEventKind } from "./ThreadEventCommandEventKind";
import type { ThreadWorkflowRunProgressEvent } from "./ThreadWorkflowRunProgressEvent";
import type { UserInput } from "./UserInput";
import type { WebSearchAction } from "./WebSearchAction";

export type ThreadItem = { "type": "userMessage", id: string, content: Array<UserInput>, } | { "type": "hookPrompt", id: string, fragments: Array<HookPromptFragment>, } | { "type": "injectedContext", id: string, title: string, preview: string, sections: Array<InjectedContextSection>, } | { "type": "agentMessage", id: string, text: string, phase: MessagePhase | null, memoryCitation: MemoryCitation | null, } | { "type": "plan", id: string, text: string, } | { "type": "reasoning", id: string, summary: Array<string>, content: Array<string>, } | { "type": "commandExecution", id: string,
/**
 * The command to be executed.
 */
command: string,
/**
 * The command's working directory.
 */
cwd: AbsolutePathBuf,
/**
 * Identifier for the underlying PTY process (when available).
 */
processId: string | null, source: CommandExecutionSource, status: CommandExecutionStatus,
/**
 * Initial wait window requested by exec_command, in milliseconds.
 */
initialWaitMs: number | null,
/**
 * Notification policy requested by exec_command.
 */
notifyOn: CommandExecutionNotifyOn | null,
/**
 * A best-effort parsing of the command to understand the action(s) it will perform.
 * This returns a list of CommandAction objects because a single shell command may
 * be composed of many commands piped together.
 */
commandActions: Array<CommandAction>,
/**
 * The command's output, aggregated from stdout and stderr.
 */
aggregatedOutput: string | null,
/**
 * The command's exit code.
 */
exitCode: number | null,
/**
 * The duration of the command execution in milliseconds.
 */
durationMs: number | null, } | { "type": "commandExecutionNotification", id: string,
/**
 * The command execution item that produced this notification.
 */
commandItemId: string, kind: CommandExecutionNotificationKind,
/**
 * User-visible notification summary.
 */
message: string,
/**
 * Output text associated with an output notification.
 */
output: string | null,
/**
 * Exit code associated with an exit notification.
 */
exitCode: number | null,
/**
 * Timestamp when the notification was created.
 */
createdAtMs: number, } | { "type": "commandWait", id: string,
/**
 * Identifier of the command session being waited on.
 */
commandId: string, status: CommandWaitStatus, notification: CommandWaitNotificationKind | null, exitCode: number | null, wallTimeSeconds: number, createdAtMs: number, } | { "type": "commandWriteStdin", id: string,
/**
 * Identifier of the command session receiving stdin.
 */
commandId: string, bytesWritten: number, containsNewline: boolean, createdAtMs: number, } | { "type": "fileChange", id: string, changes: Array<FileUpdateChange>, status: PatchApplyStatus, } | { "type": "mcpToolCall", id: string, server: string, tool: string, status: McpToolCallStatus, arguments: JsonValue, mcpAppResourceUri?: string, result: McpToolCallResult | null, error: McpToolCallError | null,
/**
 * The duration of the MCP tool call in milliseconds.
 */
durationMs: number | null, } | { "type": "dynamicToolCall", id: string, namespace: string | null, tool: string, arguments: unknown, status: DynamicToolCallStatus, contentItems: Array<DynamicToolCallOutputContentItem> | null, success: boolean | null,
/**
 * The duration of the dynamic tool call in milliseconds.
 */
durationMs: number | null, } | { "type": "eventDrivenToolCall", id: string, tool: string, arguments: unknown, status: DynamicToolCallStatus, output: unknown | null, } | { "type": "eventDrivenTool", id: string, tool: string, title: string, text: string, } | { "type": "eventCommandCall", id: string, subscriptionId: string, command: string, cwd: string | null, label: string | null, status: DynamicToolCallStatus, output: unknown | null, } | { "type": "eventCommandEvent", id: string, subscriptionId: string, kind: ThreadEventCommandEventKind, label: string | null, command: string, cwd: string | null, line: string | null, sequence: number | null, exitCode: number | null, signal: string | null, message: string | null, truncated: boolean, createdAt: number, } | { "type": "workflowRunProgress", id: string, event: ThreadWorkflowRunProgressEvent, } | { "type": "collabAgentMessage", id: string, operation: CollabAgentOperation, senderThreadId: string | null, senderPath: string, recipientThreadId: string | null, recipientPath: string, otherRecipientPaths: Array<string>, content: string, triggerTurn: boolean, } | { "type": "collabAgentToolCall",
/**
 * Unique identifier for this collab tool call.
 */
id: string,
/**
 * Name of the collab tool that was invoked.
 */
tool: CollabAgentTool,
/**
 * Current status of the collab tool call.
 */
status: CollabAgentToolCallStatus,
/**
 * Thread ID of the agent issuing the collab request.
 */
senderThreadId: string,
/**
 * Canonical path of the agent issuing the collab request.
 */
senderPath: string,
/**
 * Thread ID of the receiving agent, when applicable. In case of spawn operation,
 * this corresponds to the newly spawned agent.
 */
receiverThreadIds: Array<string>,
/**
 * Canonical paths of the receiving agents, when applicable.
 */
receiverPaths: Array<string>,
/**
 * Timeout requested for wait_agent, in milliseconds, when applicable.
 */
timeoutMs: bigint | null,
/**
 * Prompt text sent as part of the collab tool call, when available.
 */
prompt: string | null,
/**
 * Model requested for the spawned agent, when applicable.
 */
model: string | null,
/**
 * Reasoning effort requested for the spawned agent, when applicable.
 */
reasoningEffort: ReasoningEffort | null,
/**
 * Last known status of the target agents, when available.
 */
agentsStates: { [key in string]?: CollabAgentState }, } | { "type": "collabAgentStatusUpdate", id: string, senderThreadId: string | null, senderPath: string, recipientThreadId: string | null, recipientPath: string, status: CollabAgentState, } | { "type": "webSearch", id: string, query: string, action: WebSearchAction | null, } | { "type": "imageView", id: string, path: AbsolutePathBuf, } | { "type": "imageGeneration", id: string, status: string, revisedPrompt: string | null, result: string, savedPath?: AbsolutePathBuf, } | { "type": "enteredReviewMode", id: string, review: string, } | { "type": "exitedReviewMode", id: string, review: string, } | { "type": "contextCompaction", id: string, replacementHistory: JsonValue | null, };
