use crate::bespoke_event_handling::apply_bespoke_event_handling;
use crate::chatgpt_config::chatgpt_config_from_core;
use crate::command_exec::CommandExecManager;
use crate::command_exec::StartCommandExecParams;
use crate::config_manager::ConfigManager;
use crate::error_code::INPUT_TOO_LARGE_ERROR_CODE;
use crate::error_code::invalid_params;
use crate::models::add_configured_model;
use crate::models::supported_models;
use crate::outgoing_message::ConnectionId;
use crate::outgoing_message::ConnectionRequestId;
use crate::outgoing_message::OutgoingMessageSender;
use crate::outgoing_message::RequestContext;
use crate::outgoing_message::ThreadScopedOutgoingMessageSender;
use crate::skills_watcher::SkillsWatcher;
use crate::thread_status::ThreadWatchManager;
use crate::thread_status::resolve_thread_status;
use app_server_protocol::Account;
use app_server_protocol::AccountLoginCompletedNotification;
use app_server_protocol::AccountUpdatedNotification;
use app_server_protocol::AddCreditsNudgeCreditType;
use app_server_protocol::AddCreditsNudgeEmailStatus;
use app_server_protocol::AppInfo;
use app_server_protocol::AppListUpdatedNotification;
use app_server_protocol::AppSummary;
use app_server_protocol::AppsListParams;
use app_server_protocol::AppsListResponse;
use app_server_protocol::AskForApproval;
use app_server_protocol::CancelLoginAccountParams;
use app_server_protocol::CancelLoginAccountResponse;
use app_server_protocol::CancelLoginAccountStatus;
use app_server_protocol::ClientInfo;
use app_server_protocol::ClientRequest;
use app_server_protocol::ClientResponsePayload;
use app_server_protocol::CodexErrorInfo;
use app_server_protocol::CollaborationModeListParams;
use app_server_protocol::CollaborationModeListResponse;
use app_server_protocol::CommandExecParams;
use app_server_protocol::CommandExecResizeParams;
use app_server_protocol::CommandExecTerminateParams;
use app_server_protocol::CommandExecWriteParams;
use app_server_protocol::ConfigWarningNotification;
use app_server_protocol::DeprecationNoticeNotification;
use app_server_protocol::DynamicToolSpec as ApiDynamicToolSpec;
use app_server_protocol::EnvironmentAddParams;
use app_server_protocol::EnvironmentAddResponse;
use app_server_protocol::ExperimentalFeature as ApiExperimentalFeature;
use app_server_protocol::ExperimentalFeatureListParams;
use app_server_protocol::ExperimentalFeatureListResponse;
use app_server_protocol::ExperimentalFeatureStage as ApiExperimentalFeatureStage;
use app_server_protocol::FeedbackUploadParams;
use app_server_protocol::FeedbackUploadResponse;
use app_server_protocol::GetAccountParams;
use app_server_protocol::GetAccountRateLimitsResponse;
use app_server_protocol::GetAccountResponse;
use app_server_protocol::GitInfo as ApiGitInfo;
use app_server_protocol::HookMetadata;
use app_server_protocol::HooksListParams;
use app_server_protocol::HooksListResponse;
use app_server_protocol::InitializeParams;
use app_server_protocol::InitializeResponse;
use app_server_protocol::ItemCompletedNotification;
use app_server_protocol::JSONRPCErrorError;
use app_server_protocol::ListMcpServerStatusParams;
use app_server_protocol::ListMcpServerStatusResponse;
use app_server_protocol::LoginAccountParams;
use app_server_protocol::LoginAccountResponse;
use app_server_protocol::LogoutAccountResponse;
use app_server_protocol::MarketplaceAddParams;
use app_server_protocol::MarketplaceAddResponse;
use app_server_protocol::MarketplaceInterface;
use app_server_protocol::MarketplaceRemoveParams;
use app_server_protocol::MarketplaceRemoveResponse;
use app_server_protocol::MarketplaceUpgradeErrorInfo;
use app_server_protocol::MarketplaceUpgradeParams;
use app_server_protocol::MarketplaceUpgradeResponse;
use app_server_protocol::McpResourceReadParams;
use app_server_protocol::McpResourceReadResponse;
use app_server_protocol::McpServerOauthLoginCompletedNotification;
use app_server_protocol::McpServerOauthLoginParams;
use app_server_protocol::McpServerOauthLoginResponse;
use app_server_protocol::McpServerRefreshResponse;
use app_server_protocol::McpServerStatus;
use app_server_protocol::McpServerStatusDetail;
use app_server_protocol::McpServerToolCallParams;
use app_server_protocol::McpServerToolCallResponse;
use app_server_protocol::MemoryResetResponse;
use app_server_protocol::MockExperimentalMethodParams;
use app_server_protocol::MockExperimentalMethodResponse;
use app_server_protocol::ModelListParams;
use app_server_protocol::ModelListResponse;
use app_server_protocol::PermissionProfileSelectionParams;
use app_server_protocol::PluginDetail;
use app_server_protocol::PluginInstallParams;
use app_server_protocol::PluginInstallResponse;
use app_server_protocol::PluginInterface;
use app_server_protocol::PluginListMarketplaceKind;
use app_server_protocol::PluginListParams;
use app_server_protocol::PluginListResponse;
use app_server_protocol::PluginMarketplaceEntry;
use app_server_protocol::PluginReadParams;
use app_server_protocol::PluginReadResponse;
use app_server_protocol::PluginShareCheckoutParams;
use app_server_protocol::PluginShareCheckoutResponse;
use app_server_protocol::PluginShareContext;
use app_server_protocol::PluginShareDeleteParams;
use app_server_protocol::PluginShareDeleteResponse;
use app_server_protocol::PluginShareDiscoverability;
use app_server_protocol::PluginShareListItem;
use app_server_protocol::PluginShareListParams;
use app_server_protocol::PluginShareListResponse;
use app_server_protocol::PluginSharePrincipal;
use app_server_protocol::PluginSharePrincipalType;
use app_server_protocol::PluginShareSaveParams;
use app_server_protocol::PluginShareSaveResponse;
use app_server_protocol::PluginShareTarget;
use app_server_protocol::PluginShareUpdateDiscoverability;
use app_server_protocol::PluginShareUpdateTargetsParams;
use app_server_protocol::PluginShareUpdateTargetsResponse;
use app_server_protocol::PluginSkillReadParams;
use app_server_protocol::PluginSkillReadResponse;
use app_server_protocol::PluginSource;
use app_server_protocol::PluginSummary;
use app_server_protocol::PluginUninstallParams;
use app_server_protocol::PluginUninstallResponse;
use app_server_protocol::RequestId;
use app_server_protocol::ReviewDelivery as ApiReviewDelivery;
use app_server_protocol::ReviewStartParams;
use app_server_protocol::ReviewStartResponse;
use app_server_protocol::ReviewTarget as ApiReviewTarget;
use app_server_protocol::SandboxMode;
use app_server_protocol::SendAddCreditsNudgeEmailParams;
use app_server_protocol::SendAddCreditsNudgeEmailResponse;
use app_server_protocol::ServerNotification;
use app_server_protocol::ServerRequestResolvedNotification;
use app_server_protocol::SkillSummary;
use app_server_protocol::SkillsConfigWriteParams;
use app_server_protocol::SkillsConfigWriteResponse;
use app_server_protocol::SkillsListParams;
use app_server_protocol::SkillsListResponse;
use app_server_protocol::SortDirection;
use app_server_protocol::Thread;
use app_server_protocol::ThreadApproveGuardianDeniedActionParams;
use app_server_protocol::ThreadApproveGuardianDeniedActionResponse;
use app_server_protocol::ThreadArchiveParams;
use app_server_protocol::ThreadArchiveResponse;
use app_server_protocol::ThreadArchivedNotification;
use app_server_protocol::ThreadBackgroundTerminalsCleanParams;
use app_server_protocol::ThreadBackgroundTerminalsCleanResponse;
use app_server_protocol::ThreadClosedNotification;
use app_server_protocol::ThreadCompactStartParams;
use app_server_protocol::ThreadCompactStartResponse;
use app_server_protocol::ThreadDecrementElicitationParams;
use app_server_protocol::ThreadDecrementElicitationResponse;
use app_server_protocol::ThreadForkParams;
use app_server_protocol::ThreadForkResponse;
use app_server_protocol::ThreadGoal;
use app_server_protocol::ThreadGoalClearParams;
use app_server_protocol::ThreadGoalClearResponse;
use app_server_protocol::ThreadGoalClearedNotification;
use app_server_protocol::ThreadGoalGetParams;
use app_server_protocol::ThreadGoalGetResponse;
use app_server_protocol::ThreadGoalSetParams;
use app_server_protocol::ThreadGoalSetResponse;
use app_server_protocol::ThreadGoalUpdatedNotification;
use thread_history::ThreadHistoryBuilder;
use app_server_protocol::ThreadIncrementElicitationParams;
use app_server_protocol::ThreadIncrementElicitationResponse;
use app_server_protocol::ThreadInjectItemsParams;
use app_server_protocol::ThreadInjectItemsResponse;
use app_server_protocol::ThreadItem;
use app_server_protocol::ThreadListCwdFilter;
use app_server_protocol::ThreadListParams;
use app_server_protocol::ThreadListResponse;
use app_server_protocol::ThreadLoadedListParams;
use app_server_protocol::ThreadLoadedListResponse;
use app_server_protocol::ThreadMemoryModeSetParams;
use app_server_protocol::ThreadMemoryModeSetResponse;
use app_server_protocol::ThreadMetadataGitInfoUpdateParams;
use app_server_protocol::ThreadMetadataUpdateParams;
use app_server_protocol::ThreadMetadataUpdateResponse;
use app_server_protocol::ThreadNameUpdatedNotification;
use app_server_protocol::ThreadReadParams;
use app_server_protocol::ThreadReadResponse;
use app_server_protocol::ThreadRealtimeAppendAudioParams;
use app_server_protocol::ThreadRealtimeAppendAudioResponse;
use app_server_protocol::ThreadRealtimeAppendTextParams;
use app_server_protocol::ThreadRealtimeAppendTextResponse;
use app_server_protocol::ThreadRealtimeListVoicesResponse;
use app_server_protocol::ThreadRealtimeStartParams;
use app_server_protocol::ThreadRealtimeStartResponse;
use app_server_protocol::ThreadRealtimeStartTransport;
use app_server_protocol::ThreadRealtimeStopParams;
use app_server_protocol::ThreadRealtimeStopResponse;
use app_server_protocol::ThreadResumeParams;
use app_server_protocol::ThreadResumeResponse;
use app_server_protocol::ThreadRollbackParams;
use app_server_protocol::ThreadSetNameParams;
use app_server_protocol::ThreadSetNameResponse;
use app_server_protocol::ThreadShellCommandParams;
use app_server_protocol::ThreadShellCommandResponse;
use app_server_protocol::ThreadSortKey;
use app_server_protocol::ThreadSourceKind;
use app_server_protocol::ThreadStartParams;
use app_server_protocol::ThreadStartResponse;
use app_server_protocol::ThreadStartedNotification;
use app_server_protocol::ThreadStatus;
use app_server_protocol::ThreadTurnsItemsListParams;
use app_server_protocol::ThreadTurnsListParams;
use app_server_protocol::ThreadTurnsListResponse;
use app_server_protocol::ThreadUnarchiveParams;
use app_server_protocol::ThreadUnarchiveResponse;
use app_server_protocol::ThreadUnarchivedNotification;
use app_server_protocol::ThreadUnsubscribeParams;
use app_server_protocol::ThreadUnsubscribeResponse;
use app_server_protocol::ThreadUnsubscribeStatus;
use app_server_protocol::Turn;
use app_server_protocol::TurnEnvironmentParams;
use app_server_protocol::TurnError;
use app_server_protocol::TurnInterruptParams;
use app_server_protocol::TurnInterruptResponse;
use app_server_protocol::TurnItemsView;
use app_server_protocol::TurnStartParams;
use app_server_protocol::TurnStartResponse;
use app_server_protocol::TurnStatus;
use app_server_protocol::TurnSteerParams;
use app_server_protocol::TurnSteerResponse;
use app_server_protocol::UserInput as V2UserInput;
use app_server_protocol::WindowsSandboxReadiness;
use app_server_protocol::WindowsSandboxReadinessResponse;
use app_server_protocol::WindowsSandboxSetupCompletedNotification;
use app_server_protocol::WindowsSandboxSetupMode;
use app_server_protocol::WindowsSandboxSetupStartParams;
use app_server_protocol::WindowsSandboxSetupStartResponse;
use chrono::Duration as ChronoDuration;
use chrono::SecondsFormat;
use codex_analytics::AnalyticsEventsClient;
use codex_analytics::AnalyticsJsonRpcError;
use codex_analytics::InputError;
use codex_analytics::TurnSteerRequestError;
use codex_arg0::Arg0DispatchPaths;
use codex_auth_types::AuthMode;
use codex_auth_types::RequestAuthSnapshot;
use openai_backend_client::AddCreditsNudgeCreditType as BackendAddCreditsNudgeCreditType;
use openai_backend_client::Client as BackendClient;
use codex_chatgpt::connectors as chatgpt_connectors;
use codex_chatgpt::workspace_settings;
use config_service::project_trust_key;
use config_service::CloudRequirementsLoadError;
use config_service::CloudRequirementsLoadErrorCode;
use config_service::ConfigLayerStack;
use codex_config_types::McpServerTransportConfig;
use codex_exec_server::EnvironmentManager;
use codex_exec_server::LOCAL_FS;
use codex_features::FEATURES;
use codex_features::Feature;
use codex_features::Stage;
use codex_feedback::CodexFeedback;
use codex_feedback::FeedbackAttachmentPath;
use codex_feedback::FeedbackUploadOptions;
use codex_git_info::resolve_root_git_project_for_trust;
use codex_login::AuthManager;
use codex_login::CLIENT_ID;
use codex_login::CodexAuth;
use codex_login::ServerOptions as LoginServerOptions;
use codex_login::ShutdownHandle;
use codex_login::auth::login_with_chatgpt_auth_tokens;
use codex_login::complete_device_code_login;
use codex_login::login_with_api_key;
use codex_login::request_device_code;
use codex_login::run_login_server;
use codex_rmcp_client::perform_oauth_login_return_url;
use codex_sandboxing::WindowsSandboxLevelExt;
use codex_sandboxing::WindowsSandboxSetupMode as CoreWindowsSandboxSetupMode;
use codex_sandboxing::WindowsSandboxSetupRequest;
use codex_sandboxing::sandbox_setup_is_complete;
use codex_utils_absolute_path::AbsolutePathBuf;
use codex_utils_pty::DEFAULT_OUTPUT_BYTES_CAP;
use command_service::create_env;
use command_service_api::ExecCapturePolicy;
use command_service_api::ExecExpiration;
use command_service_api::ExecParams;
use mcp_service as core_connectors;
use mcp_service::McpServerStatusSnapshot;
use mcp_service::McpSnapshotDetail;
use mcp_service::collect_mcp_server_status_snapshot_with_detail;
use mcp_service::discover_supported_scopes;
use mcp_service::read_mcp_resource as read_mcp_resource_without_thread;
use mcp_service_api::McpRuntimeEnvironment;
use mcp_types::effective_mcp_servers;
use mcp_types::resolve_oauth_scopes;
use memory_service::clear_memory_roots_contents;
use model_service::builtin_collaboration_mode_presets;
use model_service::create_model_provider;
use model_service_api::ProviderAccountError;
use plugin_service::OPENAI_CURATED_MARKETPLACE_NAME;
use plugin_service::PluginInstallError as CorePluginInstallError;
use plugin_service::PluginInstallRequest;
use plugin_service::PluginLoadOutcome;
use plugin_service::PluginReadRequest;
use plugin_service::PluginUninstallError as CorePluginUninstallError;
use plugin_service::PluginsManager;
use plugin_service::RemoteMarketplace;
use plugin_service::RemoteMarketplaceSource;
use plugin_service::RemotePluginCatalogError;
use plugin_service::RemotePluginDetail as RemoteCatalogPluginDetail;
use plugin_service::RemotePluginServiceConfig;
use plugin_service::RemotePluginShareContext as RemoteCatalogPluginShareContext;
use plugin_service::RemotePluginShareSummary as RemoteCatalogPluginShareSummary;
use plugin_service::RemotePluginSummary as RemoteCatalogPluginSummary;
use plugin_service::loader::load_plugin_apps;
use plugin_service::loader::load_plugin_mcp_servers;
use plugin_service::loader::plugin_telemetry_metadata_from_root;
use plugin_service::manifest::PluginManifestInterface;
use plugin_service::marketplace::MarketplaceError;
use plugin_service::marketplace::MarketplacePluginSource;
use plugin_service::marketplace_add::MarketplaceAddError;
use plugin_service::marketplace_add::MarketplaceAddRequest;
use plugin_service::marketplace_add::add_marketplace as add_marketplace_to_codex_home;
use plugin_service::marketplace_remove::MarketplaceRemoveError;
use plugin_service::marketplace_remove::MarketplaceRemoveRequest as CoreMarketplaceRemoveRequest;
use plugin_service::marketplace_remove::remove_marketplace;
use protocol::ThreadId;
use protocol::config_types::CollaborationMode;
use protocol::config_types::ForcedLoginMethod;
use protocol::config_types::Personality;
use protocol::config_types::TrustLevel;
use protocol::config_types::WindowsSandboxLevel;
use protocol::dynamic_tools::DynamicToolSpec as CoreDynamicToolSpec;
use protocol::error::CodexErr;
use protocol::error::Result as CodexResult;
use protocol::models::ResponseItem;
use protocol::models::SandboxPermissions;
use protocol::permissions::FileSystemSandboxPolicy;
use protocol::protocol::AgentStatus;
use protocol::protocol::ConversationAudioParams;
use protocol::protocol::ConversationStartParams;
use protocol::protocol::ConversationStartTransport;
use protocol::protocol::ConversationTextParams;
#[cfg(test)]
use protocol::protocol::GitInfo as CoreGitInfo;
use protocol::protocol::InitialHistory;
use protocol::protocol::McpAuthStatus as CoreMcpAuthStatus;
use protocol::protocol::Op;
use protocol::protocol::RateLimitSnapshot as CoreRateLimitSnapshot;
use protocol::protocol::RealtimeVoicesList;
use protocol::protocol::ResumedHistory;
use protocol::protocol::ReviewDelivery as CoreReviewDelivery;
use protocol::protocol::ReviewRequest;
use protocol::protocol::ReviewTarget as CoreReviewTarget;
use protocol::protocol::RolloutItem;
use protocol::protocol::SessionConfiguredEvent;
#[cfg(test)]
use protocol::protocol::SessionMetaLine;
use protocol::protocol::TurnEnvironmentSelection;
use protocol::protocol::USER_MESSAGE_BEGIN;
use protocol::protocol::W3cTraceContext;
use protocol::user_input::MAX_USER_INPUT_TEXT_CHARS;
use protocol::user_input::UserInput as CoreInputItem;
use rollout::EventPersistenceMode;
#[cfg(test)]
use rollout::SessionMeta;
use rollout::is_persisted_rollout_item;
#[cfg(test)]
use rollout::read_head_for_summary;
use rollout::state_db::StateDbHandle;
use rollout::state_db::reconcile_rollout;
use state::ThreadMetadata;
use state::log_db::LogDbLayer;
use state_api::ExternalGoalPreviousStatus;
use state_api::ExternalGoalSet;
use std::collections::HashMap;
use std::collections::HashSet;
use std::io::Error as IoError;
use std::path::Path;
use std::path::PathBuf;
use std::result::Result;
use std::sync::Arc;
use std::time::Duration;
use std::time::Instant;
use thread_service::ForkSnapshot;
use thread_service::NewThread;
use thread_service::StartThreadOptions;
use thread_service::SteerInputError;
use thread_service::ThreadService;
use thread_service::config::Config;
use thread_service::config::ConfigOverrides;
use thread_service::config::NetworkProxyAuditMetadata;
use thread_service::config::edit::ConfigEdit;
use thread_service::config::edit::ConfigEditsBuilder;
use thread_service::path_utils;
use thread_service_api::ActiveEventSubscriptionTracker;
use thread_service_api::AppServerClientInfo;
use thread_service_api::CodexThreadTurnContextOverrides;
use thread_service_api::LiveThreadInfo;
use thread_service_api::LiveThreadRegistry;
use thread_service_api::LiveThreadSnapshot;
use thread_service_api::ThreadConfigSnapshot;
use thread_service_api::ThreadCreatedEvent;
use thread_store::ArchiveThreadParams as StoreArchiveThreadParams;
use thread_store::GitInfoPatch as StoreGitInfoPatch;
use thread_store::ListThreadsParams as StoreListThreadsParams;
use thread_store::LocalThreadStore;
use thread_store::ReadThreadByRolloutPathParams as StoreReadThreadByRolloutPathParams;
use thread_store::ReadThreadParams as StoreReadThreadParams;
use thread_store::SortDirection as StoreSortDirection;
use thread_store::StoredThread;
use thread_store::ThreadMetadataPatch as StoreThreadMetadataPatch;
use thread_store::ThreadSortKey as StoreThreadSortKey;
use thread_store::ThreadStore;
use thread_store::ThreadStoreError;
use tokio::sync::Mutex;
use tokio::sync::Semaphore;
use tokio::sync::SemaphorePermit;
use tokio::sync::broadcast;
use tokio::sync::oneshot;
use tokio::sync::watch;
use tokio_util::sync::CancellationToken;
use tokio_util::task::TaskTracker;
use toml::Value as TomlValue;
use tracing::Instrument;
use tracing::error;
use tracing::info;
use tracing::warn;
use uuid::Uuid;

#[cfg(test)]
use app_server_protocol::ServerRequest;

mod account_processor;
mod apps_processor;
mod catalog_processor;
mod command_exec_processor;
mod config_processor;
mod context_usage_replay;
mod environment_processor;
mod external_agent_config_processor;
mod feedback_doctor_report;
mod feedback_processor;
mod fs_processor;
mod initialize_processor;
mod marketplace_processor;
mod mcp_processor;
mod plugins;
mod process_exec_processor;
mod remote_control_processor;
mod search;
mod thread_processor;
mod token_usage_replay;
mod turn_processor;
mod windows_sandbox_processor;
mod workflow_processor;

pub(crate) use account_processor::AccountRequestProcessor;
pub(crate) use apps_processor::AppsRequestProcessor;
pub(crate) use catalog_processor::CatalogRequestProcessor;
pub(crate) use command_exec_processor::CommandExecRequestProcessor;
pub(crate) use config_processor::ConfigRequestProcessor;
pub(crate) use environment_processor::EnvironmentRequestProcessor;
pub(crate) use external_agent_config_processor::ExternalAgentConfigRequestProcessor;
pub(crate) use feedback_processor::FeedbackRequestProcessor;
pub(crate) use fs_processor::FsRequestProcessor;
pub(crate) use initialize_processor::InitializeRequestProcessor;
pub(crate) use marketplace_processor::MarketplaceRequestProcessor;
pub(crate) use mcp_processor::McpRequestProcessor;
pub(crate) use plugins::PluginRequestProcessor;
pub(crate) use process_exec_processor::ProcessExecRequestProcessor;
pub(crate) use remote_control_processor::RemoteControlRequestProcessor;
pub(crate) use search::SearchRequestProcessor;
pub(crate) use thread_goal_processor::ThreadGoalRequestProcessor;
pub(crate) use thread_processor::ThreadRequestProcessor;
pub(crate) use turn_processor::TurnRequestProcessor;
pub(crate) use windows_sandbox_processor::WindowsSandboxRequestProcessor;
pub(crate) use workflow_processor::WorkflowRequestProcessor;

use crate::error_code::internal_error;
use crate::error_code::invalid_request;
use crate::filters::compute_source_filters;
use crate::filters::source_kind_matches;
use crate::thread_state::ConnectionCapabilities;
use crate::thread_state::ThreadListenerCommand;
use crate::thread_state::ThreadState;
use crate::thread_state::ThreadStateManager;
use context_usage_replay::send_thread_context_usage_update_to_connection;
use token_usage_replay::latest_token_usage_turn_id_from_rollout_items;
use token_usage_replay::send_thread_token_usage_update_to_connection;

#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq)]
struct ConversationGitInfo {
    sha: Option<String>,
    branch: Option<String>,
    origin_url: Option<String>,
}

#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct ConversationSummary {
    conversation_id: ThreadId,
    path: PathBuf,
    preview: String,
    timestamp: Option<String>,
    updated_at: Option<String>,
    model_provider: String,
    cwd: PathBuf,
    cli_version: String,
    source: protocol::protocol::SessionSource,
    git_info: Option<ConversationGitInfo>,
}

mod config_errors;
mod request_errors;
mod thread_goal_processor;
mod thread_lifecycle;
mod thread_resume_redaction;
mod thread_summary;

use self::config_errors::*;
use self::request_errors::*;
use self::thread_goal_processor::api_thread_goal_from_state;
use self::thread_lifecycle::*;
use self::thread_resume_redaction::*;
use self::thread_summary::*;

pub(crate) use self::thread_lifecycle::populate_thread_turns_from_history;
pub(crate) use self::thread_processor::thread_from_stored_thread;
#[cfg(test)]
pub(crate) use self::thread_summary::read_summary_from_rollout;
#[cfg(test)]
pub(crate) use self::thread_summary::summary_to_thread;

pub(crate) fn build_api_turns_from_rollout_items(items: &[RolloutItem]) -> Vec<Turn> {
    let mut builder = ThreadHistoryBuilder::new();
    for item in items {
        if is_persisted_rollout_item(item, EventPersistenceMode::Limited) {
            builder.handle_rollout_item(item);
        }
    }
    builder.finish()
}
