[package]
name = "codex-thread-service-sample"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
approval-service = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
codex-arg0 = { workspace = true }
codex-app-server-protocol = { workspace = true }
codex-code-mode-api = { workspace = true }
codex-config-types = { workspace = true }
codex-exec-server = { workspace = true }
codex-extension-api = { workspace = true }
codex-features = { workspace = true }
goal-service = { workspace = true }
codex-login = { workspace = true, features = ["model-provider-auth"] }
mcp-service = { workspace = true }
codex-model-provider = { workspace = true }
codex-model-provider-info = { workspace = true }
codex-command-service = { workspace = true }
codex-protocol = { workspace = true }
codex-rollout = { workspace = true }
codex-state-api = { workspace = true }
thread-service-api = { workspace = true }
thread-service = { workspace = true }
codex-thread-store = { workspace = true }
codex-tool-config = { workspace = true }
codex-tool-service = { workspace = true }
codex-utils-absolute-path = { workspace = true }
codex-workflow = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
