[package]
edition.workspace = true
license.workspace = true
name = "codex-code-mode-api"
version.workspace = true

[lib]
doctest = false
name = "codex_code_mode_api"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
protocol = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
