[package]
name = "codex-sandboxing-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "codex_sandboxing_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
codex-network-proxy-api = { workspace = true }
codex-permissions-runtime = { workspace = true }
codex-protocol = { workspace = true }
codex-utils-absolute-path = { workspace = true }
codex-utils-path = { workspace = true }
dunce = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
