#![deny(clippy::print_stdout, clippy::print_stderr)]

mod certs;
mod config;
mod connect_policy;
mod http_proxy;
mod mitm;
mod network_policy;
mod policy;
mod proxy;
mod reasons;
mod responses;
mod runtime;
mod socks5;
mod state;
mod upstream;

pub use codex_network_proxy_api::ALL_PROXY_ENV_KEYS;
pub use codex_network_proxy_api::ALLOW_LOCAL_BINDING_ENV_KEY;
#[cfg(target_os = "macos")]
pub use codex_network_proxy_api::CODEX_PROXY_GIT_SSH_COMMAND_MARKER;
pub use codex_network_proxy_api::DEFAULT_NO_PROXY_VALUE;
pub use codex_network_proxy_api::NO_PROXY_ENV_KEYS;
pub use codex_network_proxy_api::NetworkProxyConstraintError;
pub use codex_network_proxy_api::NetworkProxyConstraints;
pub use codex_network_proxy_api::NetworkProxyRuntimeSnapshot;
pub use codex_network_proxy_api::PROXY_ACTIVE_ENV_KEY;
pub use codex_network_proxy_api::PROXY_ENV_KEYS;
#[cfg(target_os = "macos")]
pub use codex_network_proxy_api::PROXY_GIT_SSH_COMMAND_ENV_KEY;
pub use codex_network_proxy_api::PROXY_URL_ENV_KEYS;
pub use codex_network_proxy_api::PartialNetworkConfig;
pub use codex_network_proxy_api::PartialNetworkProxyConfig;
pub use codex_network_proxy_api::has_proxy_url_env_vars;
pub use codex_network_proxy_api::host_and_port_from_network_addr;
pub use codex_network_proxy_api::proxy_url_env_value;
pub use config::NetworkDomainPermission;
pub use config::NetworkDomainPermissionEntry;
pub use config::NetworkDomainPermissions;
pub use config::NetworkMode;
pub use config::NetworkProxyConfig;
pub use config::NetworkUnixSocketPermission;
pub use config::NetworkUnixSocketPermissions;
pub use network_policy::NetworkDecision;
pub use network_policy::NetworkDecisionSource;
pub use network_policy::NetworkPolicyDecider;
pub use network_policy::NetworkPolicyDecision;
pub use network_policy::NetworkPolicyRequest;
pub use network_policy::NetworkPolicyRequestArgs;
pub use network_policy::NetworkProtocol;
pub use policy::normalize_host;
pub use proxy::Args;
pub use proxy::NetworkProxy;
pub use proxy::NetworkProxyBuilder;
pub use proxy::NetworkProxyHandle;
pub use runtime::BlockedRequest;
pub use runtime::BlockedRequestArgs;
pub use runtime::BlockedRequestObserver;
pub use runtime::ConfigReloader;
pub use runtime::ConfigState;
pub use runtime::NetworkProxyState;
pub use state::NetworkProxyAuditMetadata;
pub use state::build_config_state;
pub use state::validate_policy_against_constraints;
