[package]
edition.workspace = true
license.workspace = true
name = "codex-tool-service-api"
version.workspace = true

[lib]
doctest = false
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
codex-command-service-api = { workspace = true }
codex-extension-api = { workspace = true }
codex-mcp-tool-types = { workspace = true }
codex-protocol = { workspace = true }
thread-service-api = { workspace = true }
codex-tool-config = { workspace = true }
codex-tool-types = { workspace = true }
serde_json = { workspace = true }
tokio-util = { workspace = true }
