//! Shared tool definitions and Responses API tool primitives that can live
//! outside `codex-core`.

mod code_mode;
mod dynamic_tool;
mod hosted_spec;
mod image_detail;
#[cfg(test)]
mod json_schema;
mod mcp_tool;
mod request_plugin_install;
mod responses_api;
mod tool_config;
mod tool_definition;
mod tool_discovery;
mod tool_plan;
mod tool_registry_plan;
mod tool_search_runtime;
#[cfg(test)]
mod tool_spec;
mod tool_specs;

pub use code_mode::augment_tool_spec_for_code_mode;
pub use code_mode::code_mode_name_for_tool_name;
pub use code_mode::collect_code_mode_exec_prompt_tool_definitions;
pub use code_mode::collect_code_mode_tool_definitions;
pub use code_mode::tool_spec_to_code_mode_tool_definition;
pub use codex_tool_types::AdditionalProperties;
pub use codex_tool_types::FreeformTool;
pub use codex_tool_types::FreeformToolFormat;
pub use codex_tool_types::FunctionCallError;
pub use codex_tool_types::JsonSchema;
pub use codex_tool_types::JsonSchemaPrimitiveType;
pub use codex_tool_types::JsonSchemaType;
pub use codex_tool_types::JsonToolOutput;
pub use codex_tool_types::LoadableToolSpec;
pub use codex_tool_types::ResponsesApiNamespace;
pub use codex_tool_types::ResponsesApiNamespaceTool;
pub use codex_tool_types::ResponsesApiTool;
pub use codex_tool_types::ResponsesApiWebSearchFilters;
pub use codex_tool_types::ResponsesApiWebSearchUserLocation;
pub use codex_tool_types::ToolCall;
pub use codex_tool_types::ToolCallSource;
pub use codex_tool_types::ToolExecutor;
pub use codex_tool_types::ToolExecutorFuture;
pub use codex_tool_types::ToolExposure;
pub use codex_tool_types::ToolInvocationMetadata;
pub use codex_tool_types::ToolName;
pub use codex_tool_types::ToolOutput;
pub use codex_tool_types::ToolPayload;
pub use codex_tool_types::ToolSearchOutput;
pub use codex_tool_types::ToolSpec;
pub use codex_tool_types::coalesce_loadable_tool_specs;
pub use codex_tool_types::create_tools_json_for_responses_api;
pub use codex_tool_types::default_namespace_description;
pub use codex_tool_types::parse_tool_input_schema;
pub use dynamic_tool::parse_dynamic_tool;
pub use hosted_spec::WebSearchToolOptions;
pub use hosted_spec::create_image_generation_tool;
pub use hosted_spec::create_web_search_tool;
pub use image_detail::can_request_original_image_detail;
pub use image_detail::normalize_output_image_detail;
pub use image_detail::sanitize_original_image_detail;
pub use mcp_tool::mcp_call_tool_result_output_schema;
pub use mcp_tool::parse_mcp_tool;
pub use request_plugin_install::REQUEST_PLUGIN_INSTALL_APPROVAL_KIND_VALUE;
pub use request_plugin_install::REQUEST_PLUGIN_INSTALL_PERSIST_ALWAYS_VALUE;
pub use request_plugin_install::REQUEST_PLUGIN_INSTALL_PERSIST_KEY;
pub use request_plugin_install::RequestPluginInstallArgs;
pub use request_plugin_install::RequestPluginInstallElicitationForm;
pub use request_plugin_install::RequestPluginInstallElicitationRequest;
pub use request_plugin_install::RequestPluginInstallElicitationSchema;
pub use request_plugin_install::RequestPluginInstallMeta;
pub use request_plugin_install::RequestPluginInstallResult;
pub use request_plugin_install::all_requested_connectors_picked_up;
pub use request_plugin_install::build_request_plugin_install_elicitation_request;
pub use request_plugin_install::verified_connector_install_completed;
pub use responses_api::dynamic_tool_to_responses_api_tool;
pub use responses_api::mcp_tool_to_deferred_responses_api_tool;
pub use responses_api::mcp_tool_to_responses_api_tool;
pub use responses_api::tool_definition_to_responses_api_tool;
pub use tool_config::ShellCommandBackendConfig;
pub use tool_config::ToolEnvironmentMode;
pub use tool_config::ToolUserShellType;
pub use tool_config::ToolsConfig;
pub use tool_config::ToolsConfigParams;
pub use tool_config::UnifiedExecShellMode;
pub use tool_config::ZshForkConfig;
pub use tool_config::request_user_input_available_modes;
pub use tool_definition::ToolDefinition;
pub use tool_discovery::DiscoverablePluginInfo;
pub use tool_discovery::DiscoverableTool;
pub use tool_discovery::DiscoverableToolAction;
pub use tool_discovery::DiscoverableToolType;
pub use tool_discovery::REQUEST_PLUGIN_INSTALL_TOOL_NAME;
pub use tool_discovery::RequestPluginInstallEntry;
pub use tool_discovery::TOOL_SEARCH_DEFAULT_LIMIT;
pub use tool_discovery::TOOL_SEARCH_TOOL_NAME;
pub use tool_discovery::ToolSearchEntry;
pub use tool_discovery::ToolSearchInfo;
pub use tool_discovery::ToolSearchSourceInfo;
pub use tool_discovery::collect_request_plugin_install_entries;
pub use tool_discovery::filter_request_plugin_install_discoverable_tools_for_client;
pub use tool_plan::CodeModeExecPlan;
pub use tool_plan::PlannedToolRegistry;
pub use tool_plan::code_mode_exec_plan_for_specs;
pub use tool_plan::filter_tool_specs_for_agent;
pub use tool_plan::hosted_model_tool_specs;
pub use tool_plan::merge_tool_specs_into_namespaces;
pub use tool_plan::plan_tool_registry_entries;
pub use tool_plan::tool_name_matches_patterns;
pub use tool_registry_plan::DuplicateToolName;
pub use tool_registry_plan::ToolRegistryEntry;
pub use tool_registry_plan::ToolRegistryPlan;
pub use tool_registry_plan::ToolRegistryPlanBuilder;
pub use tool_search_runtime::ToolSearchRuntime;
pub use tool_specs::CREATE_GOAL_TOOL_NAME;
pub use tool_specs::CommandToolOptions;
pub use tool_specs::GET_GOAL_TOOL_NAME;
pub use tool_specs::REQUEST_USER_INPUT_TOOL_NAME;
pub use tool_specs::SpawnAgentToolOptions;
pub use tool_specs::UPDATE_GOAL_TOOL_NAME;
pub use tool_specs::ViewImageToolOptions;
pub use tool_specs::WORKFLOW_ABORT_TOOL_NAME;
pub use tool_specs::WORKFLOW_DESCRIBE_TOOL_NAME;
pub use tool_specs::WORKFLOW_LIST_TOOL_NAME;
pub use tool_specs::WORKFLOW_RESUME_TOOL_NAME;
pub use tool_specs::WORKFLOW_START_TOOL_NAME;
pub use tool_specs::WORKFLOW_STATUS_TOOL_NAME;
pub use tool_specs::create_apply_patch_freeform_tool;
pub use tool_specs::create_close_agent_tool_v2;
pub use tool_specs::create_code_mode_tool;
pub use tool_specs::create_code_mode_wait_tool;
pub use tool_specs::create_command_wait_tool;
pub use tool_specs::create_create_goal_tool;
pub use tool_specs::create_exec_command_tool;
pub use tool_specs::create_exec_command_tool_with_environment_id;
pub use tool_specs::create_followup_task_tool;
pub use tool_specs::create_get_goal_tool;
pub use tool_specs::create_list_agents_tool;
pub use tool_specs::create_list_mcp_resource_templates_tool;
pub use tool_specs::create_list_mcp_resources_tool;
pub use tool_specs::create_read_mcp_resource_tool;
pub use tool_specs::create_report_agent_job_result_tool;
pub use tool_specs::create_request_permissions_tool;
pub use tool_specs::create_request_plugin_install_tool;
pub use tool_specs::create_request_user_input_tool;
pub use tool_specs::create_shell_command_tool;
pub use tool_specs::create_spawn_agent_tool_v2;
pub use tool_specs::create_spawn_agents_on_csv_tool;
pub use tool_specs::create_test_sync_tool;
pub use tool_specs::create_tool_search_tool;
pub use tool_specs::create_update_goal_tool;
pub use tool_specs::create_update_plan_tool;
pub use tool_specs::create_view_image_tool;
pub use tool_specs::create_wait_agent_tool_v2;
pub use tool_specs::create_workflow_abort_tool;
pub use tool_specs::create_workflow_describe_tool;
pub use tool_specs::create_workflow_list_tool;
pub use tool_specs::create_workflow_resume_tool;
pub use tool_specs::create_workflow_start_tool;
pub use tool_specs::create_workflow_status_tool;
pub use tool_specs::create_write_stdin_tool;
pub use tool_specs::normalize_request_user_input_args;
pub use tool_specs::request_permissions_tool_description;
pub use tool_specs::request_user_input_tool_description;
pub use tool_specs::request_user_input_unavailable_message;
