// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientRelaunchRequestedNotification = {
/**
 * Correlation identifier for this lifecycle operation.
 */
requestId: string,
/**
 * Optional human-readable reason supplied by the runtime tool caller.
 */
reason: string | null,
/**
 * Thread that requested the client relaunch, when the request originated from a thread turn.
 */
requestedByThreadId: string | null,
/**
 * Reminder that post-relaunch continuation is handled by client bootstrap autoresume.
 */
resumeStrategy: string, };
