// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientLifecycleRecoveryRecordParams = { targetThreadId: string, recoveryIdentity: string, launcherClaimId: string, launcherEvidenceVersion: string, transactionId: string, requestId: string, failedBuildId: string, failedBuildHash: string, sourceCommit: string, requestedByThreadId: string | null, mode: string, failurePhase: string, exitCode: number | null, signal: string | null, readyTimeoutMs?: number | null, logPath: string | null, transactionPath: string | null, recoveredBuildId: string, prompt: string, evidencePath: string, };
