// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadLifecycleStatus } from "./ThreadLifecycleStatus";

export type CollabAgentState = { path: string | null, lifecycleStatus: ThreadLifecycleStatus, message: string | null, };
