// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandExecOutputStream } from "./CommandExecOutputStream";

/**
 * Base64-encoded output chunk emitted for a streaming `command/exec` request.
 *
 * These notifications are delivered to the session's currently attached
 * connection. PTY sessions can rebind delivery through `terminal/session/list`
 * after reconnect; other streaming commands remain connection-scoped.
 */
export type CommandExecOutputDeltaNotification = {
/**
 * Client-supplied, connection-scoped `processId` from the original
 * `command/exec` request.
 */
processId: string,
/**
 * Runtime generation for this process id.
 */
generation: string,
/**
 * Monotonic byte-chunk sequence within this generation.
 */
sequence: bigint,
/**
 * Output stream for this chunk.
 */
stream: CommandExecOutputStream,
/**
 * Base64-encoded output bytes.
 */
deltaBase64: string,
/**
 * `true` on the final streamed chunk for a stream when `outputBytesCap`
 * truncated later output on that stream.
 */
capReached: boolean, };
