// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "./AbsolutePathBuf";
import type { CommandAction } from "./CommandAction";
import type { ExecPolicyAmendment } from "./ExecPolicyAmendment";
import type { NetworkApprovalContext } from "./NetworkApprovalContext";
import type { NetworkPolicyAmendment } from "./NetworkPolicyAmendment";

export type CommandExecutionRequestApprovalParams = {threadId: string, turnId: string, itemId: string, startedAtMs: number, approvalId?: string | null, reason?: string | null, networkApprovalContext?: NetworkApprovalContext | null, command?: string | null, cwd?: AbsolutePathBuf | null, commandActions?: Array<CommandAction> | null, proposedExecpolicyAmendment?: ExecPolicyAmendment | null, proposedNetworkPolicyAmendments?: Array<NetworkPolicyAmendment> | null};
