// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PTY lifecycle notification emitted once a user-owned terminal has started.
 *
 * `generation` is allocated by the server for this concrete process lifetime;
 * clients must use it for subsequent terminal control requests.
 */
export type CommandExecStartedNotification = { processId: string, generation: string,
/**
 * Server-generated capability required to reattach this user PTY from a
 * different app-server connection.
 */
resumeToken: string, };
