// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal lifecycle notification for a client-owned command session.
 */
export type CommandExecExitedNotification = { processId: string, generation: string, exitCode: number, };
