// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InjectedContextSection } from "./InjectedContextSection";
import type { MemoryCitation } from "./MemoryCitation";
import type { MessagePhase } from "./MessagePhase";
import type { UserInput } from "./UserInput";

export type ContextCompactionReplacementItem = { "type": "injectedContext", id: string, title: string, preview: string, sections: Array<InjectedContextSection>, } | { "type": "userMessage", id: string, content: Array<UserInput>, } | { "type": "agentMessage", id: string, text: string, phase: MessagePhase | null, memoryCitation: MemoryCitation | null, };
