// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConversationArtifactSource = { "type": "inline", content: string, mimeType: string, language?: string, truncated?: boolean, } | { "type": "url", url: string, mimeType?: string, fallbackContent?: string, };
