// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPath } from "./AgentPath";
import type { InterAgentOperation } from "./InterAgentOperation";

export type InterAgentCommunication = { author: AgentPath, recipient: AgentPath, other_recipients: Array<AgentPath>, content: string, operation: InterAgentOperation, trigger_turn: boolean, sender_thread_id: string | null, recipient_thread_id: string | null, status: unknown | null, };
