// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InterAgentContentPart = { "type": "text", text: string, } | { "type": "image_ref", attachment_id: string, image_url: string | null, };
