// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuardianApprovalReview } from "./GuardianApprovalReview";
import type { GuardianApprovalReviewAction } from "./GuardianApprovalReviewAction";

export type ItemGuardianApprovalReviewStartedNotification = { threadId: string, turnId: string, startedAtMs: number, reviewId: string, targetItemId: string | null, review: GuardianApprovalReview, action: GuardianApprovalReviewAction, };
