// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInputItemKind } from "./ModelInputItemKind";

export type ModelContextQuarantineReference = { "reference_type": "tool_transaction", kind: ModelInputItemKind, call_id: string, } | { "reference_type": "model_item", kind: ModelInputItemKind, call_id?: string, item_id?: string, fingerprint: string, };
