// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelInputItemKind = "function_call" | "tool_search_call" | "custom_tool_call" | "local_shell_call";
