// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginShareContext } from "./PluginShareContext";
import type { PluginSource } from "./PluginSource";
import type { PluginAuthPolicy } from "./v2/PluginAuthPolicy";
import type { PluginAvailability } from "./v2/PluginAvailability";
import type { PluginInstallPolicy } from "./v2/PluginInstallPolicy";
import type { PluginInterface } from "./v2/PluginInterface";

export type PluginSummary = { id: string,
/**
 * Backend remote plugin identifier when available.
 */
remotePluginId: string | null,
/**
 * Version of the locally materialized plugin package when available.
 */
localVersion: string | null, name: string,
/**
 * Remote sharing context associated with this plugin when available.
 */
shareContext: PluginShareContext | null, source: PluginSource, installed: boolean, enabled: boolean, installPolicy: PluginInstallPolicy, authPolicy: PluginAuthPolicy,
/**
 * Availability state for installing and using the plugin.
 */
availability: PluginAvailability, interface: PluginInterface | null, keywords: Array<string>, };
