// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandExecutionNotificationKind } from "./CommandExecutionNotificationKind";
import type { CommandWaitNotificationKind } from "./CommandWaitNotificationKind";
import type { CommandWaitStatus } from "./CommandWaitStatus";
import type { ContentItem } from "./ContentItem";
import type { EventCommandEvent } from "./EventCommandEvent";
import type { EventDrivenToolTrigger } from "./EventDrivenToolTrigger";
import type { FunctionCallOutputBody } from "./FunctionCallOutputBody";
import type { InterAgentCommunication } from "./InterAgentCommunication";
import type { LocalShellAction } from "./LocalShellAction";
import type { LocalShellStatus } from "./LocalShellStatus";
import type { MessagePhase } from "./MessagePhase";
import type { ReasoningItemContent } from "./ReasoningItemContent";
import type { ReasoningItemReasoningSummary } from "./ReasoningItemReasoningSummary";
import type { ThreadGoalUpdateEventAction } from "./ThreadGoalUpdateEventAction";
import type { ThreadGoalUpdateEventSource } from "./ThreadGoalUpdateEventSource";
import type { ThreadGoalUpdateGoal } from "./ThreadGoalUpdateGoal";
import type { ThreadGoalUpdateGoalStatus } from "./ThreadGoalUpdateGoalStatus";
import type { WebSearchAction } from "./WebSearchAction";
import type { WorkflowRunProgressEvent } from "./WorkflowRunProgressEvent";

export type ResponseItem = { "type": "command_wait", command_id: string, status: CommandWaitStatus, notification: CommandWaitNotificationKind | null, exit_code: number | null, wall_time_seconds: number, wait_timeout_ms: bigint, created_at_ms: bigint, } | { "type": "command_write_stdin", command_id: string, bytes_written: number, contains_newline: boolean, created_at_ms: bigint, } | { "type": "command_execution_notification", command_item_id: string, kind: CommandExecutionNotificationKind, message: string, output: string | null, exit_code: number | null, created_at_ms: bigint, } | { "type": "workflow_run_progress", event: WorkflowRunProgressEvent, } | { "type": "event_command_event", event: EventCommandEvent, } | { "type": "event_driven_tool", trigger: EventDrivenToolTrigger, } | { "type": "inter_agent_communication", communication: InterAgentCommunication, } | { "type": "thread_goal_update", goal: ThreadGoalUpdateGoal, action: ThreadGoalUpdateEventAction, source: ThreadGoalUpdateEventSource, previous_status?: ThreadGoalUpdateGoalStatus, } | { "type": "message", role: string, content: Array<ContentItem>, phase?: MessagePhase, } | { "type": "reasoning", summary: Array<ReasoningItemReasoningSummary>, content?: Array<ReasoningItemContent>, encrypted_content: string | null, } | { "type": "local_shell_call",
/**
 * Set when using the Responses API.
 */
call_id: string | null, status: LocalShellStatus, action: LocalShellAction, } | { "type": "function_call", name: string, namespace?: string, arguments: string, call_id: string, } | { "type": "tool_search_call", call_id: string | null, status?: string, execution: string, arguments: unknown, } | { "type": "function_call_output", call_id: string, output: FunctionCallOutputBody, } | { "type": "custom_tool_call", status?: string, call_id: string, name: string, input: string, } | { "type": "custom_tool_call_output", call_id: string, name?: string, output: FunctionCallOutputBody, } | { "type": "tool_search_output", call_id: string | null, status: string, execution: string, tools: unknown[], } | { "type": "web_search_call", status?: string, action?: WebSearchAction, } | { "type": "image_generation_call", id: string, status: string, revised_prompt?: string, result: string, } | { "type": "compaction", encrypted_content: string, } | { "type": "context_compaction", encrypted_content?: string, } | { "type": "other" };
