// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttestationGenerateParams } from "./AttestationGenerateParams";
import type { ChatgptAuthTokensRefreshParams } from "./ChatgptAuthTokensRefreshParams";
import type { CommandExecutionRequestApprovalParams } from "./CommandExecutionRequestApprovalParams";
import type { DynamicToolCallParams } from "./DynamicToolCallParams";
import type { FileChangeRequestApprovalParams } from "./FileChangeRequestApprovalParams";
import type { PermissionsRequestApprovalParams } from "./PermissionsRequestApprovalParams";
import type { RequestId } from "./RequestId";
import type { ToolRequestUserInputParams } from "./ToolRequestUserInputParams";
import type { McpServerElicitationRequestParams } from "./v2/McpServerElicitationRequestParams";

/**
 * Request initiated from the server and sent to the client.
 */
export type ServerRequest = { "method": "item/commandExecution/requestApproval", id: RequestId, params: CommandExecutionRequestApprovalParams, } | { "method": "item/fileChange/requestApproval", id: RequestId, params: FileChangeRequestApprovalParams, } | { "method": "item/tool/requestUserInput", id: RequestId, params: ToolRequestUserInputParams, } | { "method": "mcpServer/elicitation/request", id: RequestId, params: McpServerElicitationRequestParams, } | { "method": "item/permissions/requestApproval", id: RequestId, params: PermissionsRequestApprovalParams, } | { "method": "item/tool/call", id: RequestId, params: DynamicToolCallParams, } | { "method": "account/chatgptAuthTokens/refresh", id: RequestId, params: ChatgptAuthTokensRefreshParams, } | { "method": "attestation/generate", id: RequestId, params: AttestationGenerateParams, };
