// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalSessionOrigin } from "./TerminalSessionOrigin";

export type TerminalSessionTerminateParams = { sessionId: string, generation: string, origin: TerminalSessionOrigin, threadId?: string | null, commandItemId?: string | null, processId: string,
/**
 * Server-generated capability for a user terminal reattachment.
 */
resumeToken?: string | null, };
