// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandExecTerminalSize } from "./CommandExecTerminalSize";
import type { TerminalSessionOrigin } from "./TerminalSessionOrigin";

export type TerminalSessionDescriptor = { sessionId: string, generation: string, origin: TerminalSessionOrigin, threadId: string | null, commandItemId: string | null, processId: string, title: string, cwd: string, replayBase64: string | null, replayTruncated: boolean,
/**
 * Sequence of the newest chunk included in `replayBase64`.
 */
replayThroughSequence: bigint,
/**
 * Current PTY size in character cells. Clients use this to replay stored
 * terminal bytes with the same width that produced them before resizing to
 * the visible viewport.
 */
size?: CommandExecTerminalSize | null, canResize: boolean, canWrite: boolean, canTerminate: boolean, };
