// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalSessionListParams = { threadId?: string | null,
/**
 * Server-generated capabilities for user terminals this client is
 * authorized to reattach.
 *
 * A caller can always see terminals it originally created. A different
 * connection must explicitly prove knowledge of one of these tokens; listing
 * never claims every live user PTY.
 */
userResumeTokens?: Array<string>, };
