// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandExecTerminalSize } from "./CommandExecTerminalSize";
import type { ThreadId } from "./ThreadId";

export type TerminalPreferredSizeUpdateParams = { threadId: ThreadId, size: CommandExecTerminalSize, };
