// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from "./AgentType";
import type { ThreadProviderCapabilities } from "./ThreadProviderCapabilities";
import type { ThreadProviderKind } from "./ThreadProviderKind";
import type { ThreadProviderModelSelection } from "./ThreadProviderModelSelection";

export type ThreadProviderDescriptor = { id: string, displayName: string, kind: ThreadProviderKind, description: string, agentTypes: Array<AgentType>, modelSelection: ThreadProviderModelSelection, capabilities: ThreadProviderCapabilities, };
