// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadContextUsageToolBucket } from "./ThreadContextUsageToolBucket";

export type ThreadContextUsageToolBreakdown = { applyPatch: ThreadContextUsageToolBucket, fileOperations: ThreadContextUsageToolBucket, commands: ThreadContextUsageToolBucket, interAgent: ThreadContextUsageToolBucket, searchMedia: ThreadContextUsageToolBucket, otherTools: ThreadContextUsageToolBucket, };
