// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadContextUsageCategoryBreakdown } from "./ThreadContextUsageCategoryBreakdown";
import type { ThreadContextUsageLoadedSkills } from "./ThreadContextUsageLoadedSkills";
import type { ThreadContextUsageToolBreakdown } from "./ThreadContextUsageToolBreakdown";

export type ThreadContextUsage = { totalBytes: number, budgetUsedPercent: number | null, categories: ThreadContextUsageCategoryBreakdown, loadedSkills: ThreadContextUsageLoadedSkills, toolBreakdown: ThreadContextUsageToolBreakdown, };
