// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadLifecycleActiveFlag } from "./ThreadLifecycleActiveFlag";
import type { ThreadLifecycleFinalStatus } from "./ThreadLifecycleFinalStatus";
import type { ThreadLifecycleWaitReason } from "./ThreadLifecycleWaitReason";

export type ThreadLifecycleStatus = { "type": "notLoaded" } | { "type": "initializing" } | { "type": "active", active_flags: Array<ThreadLifecycleActiveFlag>, } | { "type": "waiting", reason: ThreadLifecycleWaitReason, } | { "type": "final", result: ThreadLifecycleFinalStatus, } | { "type": "systemError", message?: string | null, };
