// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadContextUsageSkill } from "./ThreadContextUsageSkill";

export type ThreadContextUsageLoadedSkills = { loadedCount: number, totalCount: number | null, skills: Array<ThreadContextUsageSkill>, };
