// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalUpdateGoalStatus } from "./ThreadGoalUpdateGoalStatus";
import type { ThreadId } from "./ThreadId";

export type ThreadGoalUpdateGoal = { threadId: ThreadId, objective: string, status: ThreadGoalUpdateGoalStatus, tokenBudget?: number, tokensUsed: number, timeUsedSeconds: number, createdAt: number, updatedAt: number, };
