// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadProviderListParams = {
/**
 * Workspace path whose config should be used for native role and model discovery.
 */
cwd?: string | null, };
