// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadClientRecoveryRecordParams = { threadId: string, recoveryId: string, activationId: string, releaseId: string, reason: string, occurredAt: string, fallbackReleaseId?: string, };
