// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadProviderCapabilities = { startThread: boolean, sendInput: boolean, closeThread: boolean, listChildren: boolean, restoreThread: boolean, eventStream: boolean, spawnChild: boolean, compact: boolean, workflow: boolean, pollEvent: boolean, commandSession: boolean, permissions: boolean, dynamicTools: boolean, };
