// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "./AbsolutePathBuf";
import type { GitInfo } from "./GitInfo";
import type { SessionSource } from "./SessionSource";
import type { ThreadContextUsage } from "./ThreadContextUsage";
import type { ThreadLifecycleStatus } from "./ThreadLifecycleStatus";
import type { ThreadSkill } from "./ThreadSkill";
import type { ThreadSource } from "./ThreadSource";
import type { ThreadTokenUsage } from "./ThreadTokenUsage";
import type { Turn } from "./Turn";

export type Thread = { id: string,
/**
 * Session id shared by threads that belong to the same session tree.
 */
sessionId: string,
/**
 * Source thread id when this thread was created by forking another thread.
 */
forkedFromId: string | null,
/**
 * Usually the first user message in the thread, if available.
 */
preview: string,
/**
 * Whether the thread is ephemeral and should not be materialized on disk.
 */
ephemeral: boolean,
/**
 * Model provider used for this thread (for example, 'openai').
 */
modelProvider: string,
/**
 * Unix timestamp (in seconds) when the thread was created.
 */
createdAt: number,
/**
 * Unix timestamp (in seconds) when the thread was last updated.
 */
updatedAt: number,
/**
 * Current runtime lifecycle status for the thread.
 */
lifecycleStatus: ThreadLifecycleStatus,
/**
 * [UNSTABLE] Path to the thread on disk.
 */
path: string | null,
/**
 * Working directory captured for the thread.
 */
cwd: AbsolutePathBuf,
/**
 * Version of the CLI that created the thread.
 */
cliVersion: string,
/**
 * Origin of the thread (CLI, VSCode, codex exec, codex app-server, etc.).
 */
source: SessionSource,
/**
 * Optional analytics source classification for this thread.
 */
threadSource: ThreadSource | null,
/**
 * Optional random unique nickname assigned to an AgentControl-spawned sub-agent.
 */
agentNickname: string | null,
/**
 * Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.
 */
agentRole: string | null,
/**
 * Optional canonical agent path assigned to this thread.
 */
agentPath: string | null,
/**
 * Optional Git metadata captured when the thread was created.
 */
gitInfo: GitInfo | null,
/**
 * Optional user-facing thread title.
 */
name: string | null,
/**
 * Aggregate thread-level skill usage observed so far.
 */
skills: Array<ThreadSkill>,
/**
 * Restored aggregate thread token usage, when available.
 */
tokenUsage: ThreadTokenUsage | null,
/**
 * Restored aggregate thread context usage, when available.
 */
contextUsage: ThreadContextUsage | null,
/**
 * Populated only on responses that explicitly include display history, such as
 * `thread/resume`, `thread/rollback`, `thread/fork`, and
 * `thread/read` (when `includeTurns` is true).
 * For `thread/start`, `thread/started`, and other metadata-only Thread payloads,
 * the turns field will be an empty list.
 */
turns: Array<Turn>, };
