// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowRunStatus } from "./WorkflowRunStatus";
import type { WorkflowSummary } from "./WorkflowSummary";

export type WorkflowRun = { runId: string, workflow: WorkflowSummary, status: WorkflowRunStatus, runnerStatus: string, inputs: unknown, createdAt: number, updatedAt: number, revision: bigint, message: string, abortReason: string | null, output: unknown, error: string | null, snapshotPath: string | null, };
