// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowInputSpec } from "./WorkflowInputSpec";
import type { WorkflowSource } from "./WorkflowSource";

export type WorkflowDetails = { instructions: string, id: string, name: string, description: string, source: WorkflowSource, path: string, entry: string, version: string | null, whenToUse: Array<string>, inputs: { [key in string]?: WorkflowInputSpec }, };
