// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowRunProgressKind } from "./WorkflowRunProgressKind";
import type { JsonValue } from "./serde_json/JsonValue";

export type WorkflowRunProgressEvent = { runId: string, workflowId: string, status: JsonValue, runnerStatus: string, kind: WorkflowRunProgressKind, message: string, updatedAt: bigint, };
