[package]
edition.workspace = true
license.workspace = true
name = "thread-store-api"
version.workspace = true

[lib]
name = "thread_store_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
protocol = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
