mod app_mentions;
mod config_layers;
pub mod config_rules;
mod env_var_dependencies;
pub mod injection;
pub(crate) mod invocation_utils;
mod manager;
mod mention_counts;
pub mod model;
pub mod render;

pub use app_mentions::CollectedToolMentions;
pub use app_mentions::build_connector_slug_counts;
pub use app_mentions::collect_explicit_app_ids_from_messages;
pub use app_mentions::collect_explicit_app_ids_from_skill_items;
pub use app_mentions::collect_tool_mentions_from_messages;
pub use app_mentions::collect_tool_mentions_from_messages_with_sigil;
pub use app_mentions::filter_connectors_for_user_messages;
pub use config_layers::SkillConfigLayerEntry;
pub use config_layers::SkillConfigLayerStack;
pub use config_layers::SkillConfigLayerStackOrdering;
pub use env_var_dependencies::SkillDependencyInfo;
pub use env_var_dependencies::collect_env_var_dependencies;
pub use invocation_utils::build_implicit_skill_path_indexes;
pub use invocation_utils::detect_implicit_skill_invocation_for_command;
pub use manager::DisabledSkillService;
pub use manager::SharedSkillServiceApi;
pub use manager::SkillServiceApi;
pub use manager::SkillServiceApiFuture;
pub use manager::SkillsLoadInput;
pub use manager::bundled_skills_enabled_from_stack;
pub use mention_counts::build_skill_name_counts;
pub use model::SkillError;
pub use model::SkillLoadOutcome;
pub use model::SkillMetadata;
pub use model::SkillPolicy;
pub use model::SkillWatchPath;
pub use model::filter_skill_load_outcome_for_product;
pub use render::AvailableSkills;
pub use render::SKILLS_HOW_TO_USE_WITH_ABSOLUTE_PATHS;
pub use render::SKILLS_HOW_TO_USE_WITH_ALIASES;
pub use render::SKILLS_INTRO_WITH_ABSOLUTE_PATHS;
pub use render::SKILLS_INTRO_WITH_ALIASES;
pub use render::SkillMetadataBudget;
pub use render::SkillRenderReport;
pub use render::build_available_skills;
pub use render::default_skill_metadata_budget;
pub use render::render_available_skills_body;
