[package]
name = "codex-utils-image"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
codex-utils-string = { workspace = true }
image = { workspace = true, features = ["jpeg", "png", "gif", "webp"] }
lru = { workspace = true }
mime_guess = { workspace = true }
sha1 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
image = { workspace = true, features = ["jpeg", "png", "gif", "webp"] }
tokio = { workspace = true, features = ["fs", "rt", "rt-multi-thread", "macros"] }

[lib]
doctest = false
