[package]
edition.workspace = true
license.workspace = true
name = "codex-approval-service-api"
version.workspace = true

[lib]
name = "codex_approval_service_api"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
codex-command-service-api = { workspace = true }
codex-protocol = { workspace = true }
codex-thread-api = { workspace = true }
codex-tool-runtime-api = { workspace = true }
codex-tool-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
