pub mod config_layers;
mod discoverable;
pub mod installed_marketplaces;
pub mod loader;
mod manager;
mod mentions;
mod projections;
pub mod manifest;
pub mod marketplace;
pub mod marketplace_add;
pub mod marketplace_remove;
pub mod marketplace_upgrade;
pub mod remote_state;
pub mod remote;
pub mod startup_sync;
pub mod store;
#[cfg(test)]
mod test_support;
pub mod toggles;

pub type LoadedPlugin = plugin_service_api::LoadedPlugin<codex_config_types::McpServerConfig>;
pub type PluginLoadOutcome = plugin_service_api::PluginLoadOutcome;

pub use plugin_service_api::OPENAI_BUNDLED_MARKETPLACE_NAME;
pub use plugin_service_api::OPENAI_CURATED_MARKETPLACE_NAME;
pub use plugin_service_api::PluginsConfigInput;
pub use plugin_service_api::TOOL_SUGGEST_DISCOVERABLE_PLUGIN_ALLOWLIST;
pub use plugin_service_api::config_layers::PluginConfigLayerEntry;
pub use plugin_service_api::config_layers::PluginConfigLayerStack;
pub use discoverable::list_tool_suggest_discoverable_plugins;
pub use discoverable::load_plugin_hooks_for_config;
pub use mentions::build_plugin_injections;
pub use mentions::load_and_merge_plugin_agent_roles_for_config;
pub use mentions::collect_explicit_plugin_mentions;
pub use mentions::merge_plugin_agent_roles;
pub use projections::load_effective_plugin_skill_roots_for_config;
pub use projections::load_plugin_capability_summaries_for_config;
pub use projections::load_plugin_connector_ids_for_config;
pub use projections::load_plugin_effective_apps_for_config;
pub use projections::render_available_plugins_instructions;
pub use manager::ConfiguredMarketplace;
pub use manager::ConfiguredMarketplaceListOutcome;
pub use manager::ConfiguredMarketplacePlugin;
pub use manager::PluginAnalyticsEventSink;
pub use manager::PluginDetail;
pub use manager::PluginDetailsUnavailableReason;
pub use manager::PluginInstallError;
pub use manager::PluginInstallOutcome;
pub use manager::PluginInstallRequest;
pub use manager::PluginReadOutcome;
pub use manager::PluginReadRequest;
pub use manager::PluginUninstallError;
pub use manager::PluginsManager;
pub use manager::configured_plugins_from_stack;
pub use marketplace_upgrade::ConfiguredMarketplaceUpgradeError as PluginMarketplaceUpgradeError;
pub use marketplace_upgrade::ConfiguredMarketplaceUpgradeOutcome as PluginMarketplaceUpgradeOutcome;
pub use remote::PluginRemoteSyncError;
pub use remote::RemoteMarketplace;
pub use remote::RemoteMarketplaceSource;
pub use remote::RemotePluginAuth;
pub use remote::RemotePluginAuthFuture;
pub use remote::RemotePluginAuthProvider;
pub use remote::RemotePluginCatalogError;
pub use remote::RemotePluginDetail;
pub use remote::RemotePluginServiceConfig;
pub use remote::RemotePluginShareAccessPolicy;
pub use remote::RemotePluginShareContext;
pub use remote::RemotePluginShareDiscoverability;
pub use remote::RemotePluginSharePrincipal;
pub use remote::RemotePluginSharePrincipalRole;
pub use remote::RemotePluginSharePrincipalType;
pub use remote::RemotePluginShareSaveResult;
pub use remote::RemotePluginShareSummary;
pub use remote::RemotePluginShareTarget;
pub use remote::RemotePluginShareTargetRole;
pub use remote::RemotePluginShareUpdateDiscoverability;
pub use remote::RemotePluginShareUpdateTargetsResult;
pub use remote::RemotePluginSummary;
pub use remote::checkout_remote_plugin_share;
pub use remote::delete_remote_plugin_share;
pub use remote::fetch_remote_marketplaces;
pub use remote::fetch_remote_plugin_detail;
pub use remote::fetch_remote_plugin_detail_with_download_urls;
pub use remote::fetch_remote_plugin_share_context;
pub use remote::fetch_remote_plugin_skill_detail;
pub use remote::featured_plugin_ids_for_config;
pub use remote::install_remote_plugin;
pub use remote::is_valid_remote_plugin_id;
pub use remote::list_remote_plugin_shares;
pub use remote::load_plugin_share_remote_ids_by_local_path;
pub use remote::mark_remote_plugin_cache_mutation_in_flight;
pub use remote::maybe_start_plugin_list_background_tasks_for_config;
pub use remote::maybe_start_plugin_startup_tasks_for_config;
pub use remote::maybe_start_remote_installed_plugins_cache_refresh;
pub use remote::maybe_start_remote_installed_plugins_cache_refresh_after_mutation;
pub use remote::remote_bundle;
pub use remote::save_remote_plugin_share;
pub use remote::sync_plugins_from_remote;
pub use remote::uninstall_remote_plugin;
pub use remote::update_remote_plugin_share_targets;
pub use remote::validate_remote_plugin_id;
