mod config_layers;
pub mod config_rules;
mod env_var_dependencies;
pub mod injection;
pub(crate) mod invocation_utils;
mod manager;
mod mention_counts;
pub mod model;
pub mod render;

pub use config_layers::SkillConfigLayerEntry;
pub use config_layers::SkillConfigLayerStack;
pub use config_layers::SkillConfigLayerStackOrdering;
pub use env_var_dependencies::SkillDependencyInfo;
pub use env_var_dependencies::collect_env_var_dependencies;
pub use invocation_utils::build_implicit_skill_path_indexes;
pub use invocation_utils::detect_implicit_skill_invocation_for_command;
pub use manager::DisabledSkillsRuntime;
pub use manager::SharedSkillsRuntime;
pub use manager::SkillsLoadInput;
pub use manager::SkillsRuntime;
pub use manager::SkillsRuntimeFuture;
pub use manager::bundled_skills_enabled_from_stack;
pub use mention_counts::build_skill_name_counts;
pub use model::SkillError;
pub use model::SkillLoadOutcome;
pub use model::SkillMetadata;
pub use model::SkillPolicy;
pub use model::filter_skill_load_outcome_for_product;
pub use render::AvailableSkills;
pub use render::SKILLS_HOW_TO_USE_WITH_ABSOLUTE_PATHS;
pub use render::SKILLS_HOW_TO_USE_WITH_ALIASES;
pub use render::SKILLS_INTRO_WITH_ABSOLUTE_PATHS;
pub use render::SKILLS_INTRO_WITH_ALIASES;
pub use render::SkillMetadataBudget;
pub use render::SkillRenderReport;
pub use render::build_available_skills;
pub use render::default_skill_metadata_budget;
pub use render::render_available_skills_body;
